{% set name = "conda-suggest-conda-forge" %}
{% set version = "2021.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: f05fa6361e45bf07ad2730b31a664362cfac71f4afc75ccc0a1ad5ed73f21a07

build:
  number: 0

test:
  commands:
    - test -f $PREFIX/share/conda-suggest/conda-forge.noarch.map  # [unix]
    - test -f $PREFIX/share/conda-suggest/conda-forge.{{ build_platform }}.map  # [unix]
    - if not exist %PREFIX%\\share\\conda-suggest\\conda-forge.noarch.map exit 1  # [win]
    - if not exist %PREFIX%\\share\\conda-suggest\\conda-forge.{{ build_platform }}.map exit 1  # [win]

about:
  home: https://github.com/regro/conda-suggest-conda-forge
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda-suggest map files for conda-forge.

extra:
  recipe-maintainers:
    - scopatz
